runtime: nodejs10

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
    expiration: '10s'
  - url: /
    static_dir: build
    expiration: '10s'
  - url: /static
    static_dir: build/static
    expiration: '10s'

env_variables:
  BOOT_SCRIPT: 'react-scripts start'
  REACT_APP_API_BASE_URL: 'https://api-dot-fionas-todos-275302.ue.r.appspot.com/'
